#!/bin/bash

DEVICE=laurel_sprout
TG_USERNAME=@H3M3L
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch evolution_$DEVICE-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_metalava
