#!/bin/bash
cd /tmp/rom

DEVICE=laurel_sprout
TG_USERNAME=@HemantSachdeva

. build/envsetup.sh
lunch evolution_$DEVICE-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

# Telgram env setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"

tg_post_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1"
}

tg_error_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1" \
        -d log_file="$3"
}

# stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}


make_rom(){
	tg_post_msg "<b>$TG_USERNAME EvolutionX CI Build Triggered for $DEVICE</b>" "$CHATID"
	mka bacon -j16 | tee logs.log
	if [ -f out/target/product/$DEVICE/*zip ]; then
		zip=$(up out/target/product/$DEVICE/*zip)
		json=$(up out/target/product/$DEVICE/*zip.json)
		echo " "
		echo "$zip"
		tg_post_msg "<b>$TG_USERNAME Build Completed</b>%0A%0A<b>Link : </b> <code>"$zip"</code>" "$CHATID"
		tg_post_msg "<b>Json File</b>%0A%0A<b>Link : </b> <code>"$json"</code>" "$CHATID"
	else
		LOGS=$(up logs.log)
		tg_error_msg "<b>$TG_USERNAME Build Failed, check logs.log file</b>" "$CHATID" "$LOGS"
	fi
}

# Finally
make_rom
