#!/bin/bash

MANIFEST=git://github.com/PotatoProject/manifest-git
BRANCH=dumaloo-release
DEVICE=laurel_sprout
BRAND=xiaomi
PLATFORM=sm8150
DT_LINK=https://github.com/H3M3L/A11_laurel_sprout/tree/Potato-dumaloo
VT_LINK=https://github.com/H3M3L/A11_vendor_laurel_sprout
KT_LINK=https://github.com/H3M3L/kernel_xiaomi_laurel_sprout
IMAGE_LINK=https://gitlab.com/H3M3L/a10_laurel_sprout-images
mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name H3M3L
git config --global user.email lllooolllzzz555@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
find hardware/qcom-caf/$PLATFORM/display vendor/qcom/opensource/commonsys-intf/display vendor/qcom/opensource/wfd-commonsys .repo/ -delete
git clone https://github.com/HemantSachdeva/hardware_qcom-caf_sm8150_display hardware/qcom-caf/$PLATFORM/display
git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_display-commonsys-intf vendor/qcom/opensource/commonsys-intf/display
git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_wfd-commonsys vendor/qcom/opensource/wfd-commonsys

git clone $DT_LINK --single-branch -b elle device/$BRAND/$DEVICE
git clone $VT_LINK --single-branch -b elle vendor/$BRAND/$DEVICE
git clone $KT_LINK --single-branch -b elle kernel/$BRAND/$DEVICE
git clone $IMAGE_LINK --single-branch -b elle device/$BRAND/$DEVICE-images
